### ISSUE TITLE
feat: add `filter` command

### ISSUE THREAD

**Issue by masci** [pidgeot-org/derrik#2]
Read one or more input files in jsonl format, filter out lines matching `--what` in the fields `--where` and write the output to the stdout or file passed with `--output`.
```
derrik filter \
    --what "keyword_to_match" \
    --where "some_field" "some_other_field" \
    --operator "icontains" \
    --output out.jsonl \
    *.jsonl.zstd
```

Nice to have (next steps): 
- load keywords to match from a csv file `--what-file matches.txt`
- store the field that matched in a new field in the output `--matched-field "matched"`

**Comment by luigigubello** [comment]
`--match` should accept just a vector of strings, we should have a different option to pass a file (e.g. `--match-file matches.txt`)

**Comment by luigigubello** [comment]
`match` is a taken keyword in Rust
